# Generated by Django 5.1.7 on 2025-04-18 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('correct_option', models.CharField(max_length=1)),
                ('difficulty', models.FloatField(default=1.0)),
                ('topic', models.CharField(default='General', max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('intrinsic_difficulty', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('topic', models.CharField(default='General', max_length=100)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('questions', models.TextField(blank=True)),
                ('difficulties', models.TextField(blank=True)),
                ('times_taken', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_score', models.FloatField(default=1.0)),
                ('score', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
