# Generated by Django 5.1.7 on 2025-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='topic',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
